import type { ReportLanguage } from '../types/index.js';

interface TemplateStrings {
  reportTitle: string;
  projectSummary: string;
  techStackLabel: string;
  periodLabel: string;
  commitsLabel: string;
  problemsSolved: string;
  improvementOpportunities: string;
  growthMetrics: string;
  recommendedActions: string;
  noStories: string;
  noOpportunities: string;
  generatedBy: string;
  severity: Record<string, string>;
  difficulty: Record<string, string>;
}

const templates: Record<ReportLanguage, TemplateStrings> = {
  ko: {
    reportTitle: '포트폴리오 분석 리포트',
    projectSummary: '프로젝트 요약',
    techStackLabel: '기술 스택',
    periodLabel: '개발 기간',
    commitsLabel: '총 커밋',
    problemsSolved: '해결한 문제',
    improvementOpportunities: '개선 기회',
    growthMetrics: '성장 지표',
    recommendedActions: '추천 액션',
    noStories: '분석된 스토리가 없습니다',
    noOpportunities: '현재 발견된 개선 기회가 없습니다. 잘 작성된 코드입니다!',
    generatedBy: 'portfolio-tracker로 자동 생성됨',
    severity: { high: '높음', medium: '중간', low: '낮음' },
    difficulty: { easy: '쉬움', medium: '보통', hard: '어려움' },
  },
  en: {
    reportTitle: 'Portfolio Analysis Report',
    projectSummary: 'Project Summary',
    techStackLabel: 'Tech Stack',
    periodLabel: 'Development Period',
    commitsLabel: 'Total Commits',
    problemsSolved: 'Problems Solved',
    improvementOpportunities: 'Improvement Opportunities',
    growthMetrics: 'Growth Metrics',
    recommendedActions: 'Recommended Actions',
    noStories: 'No stories analyzed',
    noOpportunities: 'No improvement opportunities found. Well-written code!',
    generatedBy: 'Auto-generated by portfolio-tracker',
    severity: { high: 'High', medium: 'Medium', low: 'Low' },
    difficulty: { easy: 'Easy', medium: 'Medium', hard: 'Hard' },
  },
};

export function getTemplate(language: ReportLanguage): TemplateStrings {
  return templates[language];
}
